// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AccountConfirm(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AccountDelete(arg1:number):Promise<void>;

export function AccountLogin(arg1:string):Promise<void>;

export function AccountMessageSSE():Promise<void>;

export function AccountPageItems(arg1:number,arg2:number):Promise<Array<main.AccountItem>>;

export function AccountPrivateMessage(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;

export function AccountPrivateMessageCount():Promise<number>;

export function AccountSearchPhone(arg1:string):Promise<Array<main.AccountItem>>;

export function AccountSendCode(arg1:string):Promise<void>;

export function AccountSwitch(arg1:string):Promise<void>;

export function GetAppInfoStatus():Promise<boolean>;

export function SetAppInfo(arg1:string,arg2:string):Promise<void>;
