// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AccountConfirm(arg1, arg2, arg3) {
  return window['go']['main']['App']['AccountConfirm'](arg1, arg2, arg3);
}

export function AccountDelete(arg1) {
  return window['go']['main']['App']['AccountDelete'](arg1);
}

export function AccountLogin(arg1) {
  return window['go']['main']['App']['AccountLogin'](arg1);
}

export function AccountMessageSSE() {
  return window['go']['main']['App']['AccountMessageSSE']();
}

export function AccountPageItems(arg1, arg2) {
  return window['go']['main']['App']['AccountPageItems'](arg1, arg2);
}

export function AccountPrivateMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AccountPrivateMessage'](arg1, arg2, arg3, arg4);
}

export function AccountPrivateMessageCount() {
  return window['go']['main']['App']['AccountPrivateMessageCount']();
}

export function AccountSearchPhone(arg1) {
  return window['go']['main']['App']['AccountSearchPhone'](arg1);
}

export function AccountSendCode(arg1) {
  return window['go']['main']['App']['AccountSendCode'](arg1);
}

export function AccountSwitch(arg1) {
  return window['go']['main']['App']['AccountSwitch'](arg1);
}

export function GetAppInfoStatus() {
  return window['go']['main']['App']['GetAppInfoStatus']();
}

export function ScheduledDeletion() {
  return window['go']['main']['App']['ScheduledDeletion']();
}

export function SetAppInfo(arg1, arg2) {
  return window['go']['main']['App']['SetAppInfo'](arg1, arg2);
}
